### PR TITLE
Support Python 2.6

### PR DESCRIPTION
**Pull request by di**
With a few small changes, this plugin can support Python 2.6 as well.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Flake8 3.0 does not support Python 2.6, so the py26-flake83 env will fail.

Why do you need Python 2.6 support?

**Comment by di** [comment]
> Flake8 3.0 does not support Python 2.6, so the py26-flake83 env will fail.

Looks like it passed to me.

> Why do you need Python 2.6 support?

Because I'd like to use this plugin in Python 2.6 :)

**Comment by sigmavirus24** [comment]
Okay, let me ask the question differently, why can't you just run your linter on Python 2.7?

**Comment by public** [comment]
Py2.6 support was removed on purpose. Theoretically you should get different results on 2.6 since e.g. The stdlib is different but this is a yak I never saw fit to shave.

Running on 2.7 against 2.6 code should work fairly well. pyca/cryptography do it.

**Comment by di** [comment]
Fair enough! I suppose the tests are just missing those edge cases.

**Pull request closed without merging**
