### PR TITLE
Recognize zoneinfo introduced in python 3.9 as stdlib

### PR DESCRIPTION
**Pull request by AMDmi3**
Please tag a new release with this change

### CODE REVIEW

**Comment by samuelhwilliams** [comment]
Would be great to merge this within a couple of years :)

**Review by public — APPROVED** [review]

**Comment by sminozhenko** [comment]
Hi, Any chance to get this change merged

**Comment by AMDmi3** [comment]
Ping @pgjones @sigmavirus24

**Comment by AMDmi3** [comment]
@sigmavirus24 thank you so much! any chance to have a new release tagged?

**Comment by sigmavirus24** [comment]
I'm not able to release right now and unlikely to have time today even if I'm given permissions

**Comment by pgjones** [comment]
What is your pypi username?

**Comment by AMDmi3** [comment]
At least a tag would be fine too.

**Comment by sigmavirus24** [comment]
> What is your pypi username?

Same as it is on Flake8 - the first (username) portion of my email address. F rather it not be indexed by search engines though

**Pull request merged**
